In [2]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.dtype)

print(arr.shape, arr2.shape)



[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
(5,) (6,)


In [10]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [13]:
arr3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3D, type(arr3D), arr3D.dtype, arr3D.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] <class 'numpy.ndarray'> int64 (2, 2, 2)


In [24]:
#create from scratch

arr1 = np.zeros((2,3), dtype='int64') # prefill with zeros
print(arr1, arr1.shape)

arr2 = np.ones((5,), dtype='int64') # prefill with ones
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100) # prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,11) # like range function (start,stop,end)
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) # evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[  1.  34.  67. 100.] (4,)


# Array Properties

In [27]:
arr = np.array([1,2,3,4,5])

print(arr.shape) #dimensions-> m x n
print(arr.size) #tot els
print(arr.dtype) #data type
print(arr.ndim) #

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)


(5,)
5
int64
1
[1. 2. 3. 4. 5.] float64


# Operations

In [32]:
# Reshaping

arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)


flattend = arr.flatten() # 2D => 1D
print(flattend, flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [35]:
# Indexing
arr = np.array([1,2,3,4,5])

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

1
2
3
4
5


In [37]:
#fancy indexing
arr = np.array([1,2,3,4,5])
#print 0,1,3 index values

idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [42]:
#boolean indexing
arr = np.array([1,2,3,4,5])

print(arr[arr > 2])
print(arr[arr%2 == 0])
print(arr[arr%2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [51]:
# Slicing operation
# same as list
arr = np.array([1,2,3,4,5])
# (start,stop,end)

print(arr[1:4])
print(arr[1:3])
print(arr[1:])
print(arr[:3])
print(arr[::2])
print(arr[::1])
print(arr[::-1])




[2 3 4]
[2 3]
[2 3 4 5]
[1 2 3]
[1 3 5]
[1 2 3 4 5]
[5 4 3 2 1]


In [55]:
# copy vs view in slice

# SLICING
# python list -> copy
#np array -> view

nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

arr = np.array(nums)
sub_arr = arr[1:3]  # arr.copy() is used to create a new array
print(sub_arr)
sub_arr[0] = 200

print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


# Numpy Datatypes

- int8, int16, int32, int64, int128 ....
- float8, .....
- bool
- complex64, (complex128)default
- String: S (byte-str) & U (unicode-str)
- object

- string & object not preferred in real life scenarios



# Multi-dimensional Arrays & Axes
# Axes in Multi-dimensional Arrays

In [64]:
# axes = dimensions
# axis = plural-> axes
# 1D -> 1 axis
# 2D -> 2 axes [axis 0 (row), axis 1 (column)]
# 3D -> 3 axes [axis 0 (depth/layers), axis 1 (row in each layer), axis 2 (column)]

# Multi-dimensional arrays

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)

print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D, axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D,axis=1)
print(sum_of_rows)


print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


# 3D array

In [71]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

print(arr3D, arr3D.shape)

#indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:]) # first row from both layers
print(arr3D[:,:,0]) # first col from both layers

arr3D[:,0,:] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


# Vectorization & Broadcasting

In [75]:
#vectorization

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr ** 2)
print(arr +10)
print(arr+arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [78]:
# Broadcasting
# scaling our arrays without extra memory
# trailing

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)
print(arr+arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


# Normalization

In [79]:
# vector normalization
# normalizing an array means transforming its values os they fit into a specific scale or range

# std normlz (z-score) == (arr-mean)/(std deviation)
# 

In [85]:
# normalize

arr = np.array([[1,2],[3,4]])

print(np.mean(arr))
print(np.std(arr))

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev

print(normalized_arr) 

print(mean)
print(std_dev)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


# Mathematical Functions

## Aggregation
- sum()
- prod()
- min()
- max()
- mean()
- std()
- var()
- median()
- argmin()
- argmax()

## Power
- square()
- sqrt()
- pow(a,b)

## Log & Exponential
- log()
- log10()
- log2()
- exp()

## Rounding
- round()
- floor()
- ceil()
- trunc()

## Extras
- unique()
- sort()
- abs()